import { Meta, StoryFn } from "@storybook/react";
import SeatSelector from "./SeatSelector";

export default {
  title: "Components/SeatSelector",
  component: SeatSelector,
  argTypes: {
    rows: { control: "number", defaultValue: 5 },
    seatsPerRow: { control: "number", defaultValue: 6 },
    maxSelections: { control: "number", defaultValue: 5 },
    gap: { control: "number", defaultValue: 2 },
    seatSize: { control: "text", defaultValue: "40px" },
    colors: {
      control: "object",
      defaultValue: {
        booked: "bg-gray-600",
        available: "bg-purple-500",
        selected: "bg-orange-500",
      },
    },
    availableSeats: {
      control: "object",
      defaultValue: {
        R1S1: "available",
        R1S2: "available",
        R1S3: "booked",
        R1S4: "available",
        R1S5: "available",
        R1S6: "available",
        R2S1: "booked",
        R2S2: "available",
        R2S3: "available",
        R2S4: "booked",
        R2S5: "available",
        R2S6: "available",
        R3S1: "available",
        R3S2: "booked",
        R3S3: "available",
        R3S4: "available",
        R3S5: "booked",
        R3S6: "booked",
        R4S1: "available",
        R4S2: "available",
        R4S3: "available",
        R4S4: "available",
        R4S5: "booked",
        R4S6: "available",
        R5S1: "booked",
        R5S2: "available",
        R5S3: "available",
        R5S4: "available",
        R5S5: "available",
        R5S6: "available",
      },
    },
  },
} as Meta<typeof SeatSelector>;

const Template: StoryFn<typeof SeatSelector> = (args) => <SeatSelector {...args} />;

export const Default = Template.bind({});
Default.args = {
  rows: 5,
  seatsPerRow: 6,
  maxSelections: 5,
  gap: 2,
  seatSize: "40px",
  colors: {
    booked: "bg-gray-600",
    available: "bg-purple-500",
    selected: "bg-orange-500",
  },
  availableSeats: {
    R1S1: "available",
    R1S2: "available",
    R1S3: "booked",
    R1S4: "available",
    R1S5: "available",
    R1S6: "available",
    R2S1: "booked",
    R2S2: "available",
    R2S3: "available",
    R2S4: "booked",
    R2S5: "available",
    R2S6: "available",
    R3S1: "available",
    R3S2: "booked",
    R3S3: "available",
    R3S4: "available",
    R3S5: "booked",
    R3S6: "booked",
    R4S1: "available",
    R4S2: "available",
    R4S3: "available",
    R4S4: "available",
    R4S5: "booked",
    R4S6: "available",
    R5S1: "booked",
    R5S2: "available",
    R5S3: "available",
    R5S4: "available",
    R5S5: "available",
    R5S6: "available",
  },
};
